# Generated by Django 5.1.4 on 2025-01-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, upload_to='book-images'),
        ),
    ]
