# Generated by Django 5.1.4 on 2025-01-12 04:35

import books.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, storage=books.custom_storage.CustomS3Storage(), upload_to='bookStore-images/'),
        ),
    ]
