# Generated by Django 5.1.4 on 2025-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
    ]
